name: Deploy Next.js site to Pages (Dev & Release)

on:
  push:
    branches:
      - "dev"  # Auto-publish to Dev
  pull_request:
    types:
      - closed
    branches:
      - main  # Publish to Release on PR merge

  workflow_dispatch:  # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci  # or yarn install, depending on your project

      - name: Set basePath for deployment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "module.exports = { basePath: '/dev' };" > next.config.js
          else
            echo "module.exports = { basePath: '/release' };" > next.config.js
          fi

      - name: Build with Next.js
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
